UPDATE teams SET team_name = 'Galatasaray', team_power = 6.94 WHERE team_id = 1;
UPDATE teams SET team_name = 'Fenerbahçe', team_power = 6.93 WHERE team_id = 2;
UPDATE teams SET team_name = 'Beşiktaş', team_power = 6.95 WHERE team_id = 3;
UPDATE teams SET team_name = 'Trabzonspor', team_power = 6.91 WHERE team_id = 4;
UPDATE teams SET team_name = 'Altay', team_power = 6.75 WHERE team_id = 5;
UPDATE teams SET team_name = 'Gaziantepspor', team_power = 6.79 WHERE team_id = 6;
UPDATE teams SET team_name = 'Gençlerbirliği', team_power = 6.77 WHERE team_id = 7;
UPDATE teams SET team_name = 'MKE Ankaragücü', team_power = 6.73 WHERE team_id = 9;
UPDATE teams SET team_name = 'Denizlispor', team_power = 6.74 WHERE team_id = 10;
UPDATE teams SET team_name = 'Bursaspor', team_power = 6.78 WHERE team_id = 13;
UPDATE teams SET team_name = 'Adanaspor', team_power = 6.75 WHERE team_id = 14;
UPDATE teams SET team_name = 'Göztepe', team_power = 6.78 WHERE team_id = 15;
UPDATE teams SET team_name = 'Osmanlıspor FK', team_power = 6.86 WHERE team_id = 444;
UPDATE teams SET team_name = 'Sivasspor', team_power = 6.82 WHERE team_id = 446;
UPDATE teams SET team_name = 'Atiker Konyaspor', team_power = 6.84 WHERE team_id = 447;
UPDATE teams SET team_name = 'Çaykur Rizespor', team_power = 6.8 WHERE team_id = 448;
UPDATE teams SET team_name = 'Medipol Başakşehir', team_power = 6.91 WHERE team_id = 451;
UPDATE teams SET team_name = 'Mersin İdmanyurdu', team_power = 6.69 WHERE team_id = 452;
UPDATE teams SET team_name = 'Adana Demirspor', team_power = 6.89 WHERE team_id = 454;
UPDATE teams SET team_name = 'Antalyaspor', team_power = 6.8 WHERE team_id = 455;
UPDATE teams SET team_name = 'Kayseri Erciyesspor', team_power = 6.67 WHERE team_id = 459;
UPDATE teams SET team_name = 'Eskişehirspor', team_power = 6.73 WHERE team_id = 536;
UPDATE teams SET team_name = 'Fatih Karagümrük', team_power = 6.82 WHERE team_id = 537;
UPDATE teams SET team_name = 'Karabükspor', team_power = 6.65 WHERE team_id = 558;
UPDATE teams SET team_name = 'Kayserispor', team_power = 6.76 WHERE team_id = 570;
UPDATE teams SET team_name = 'Gaziantep FK', team_power = 6.79 WHERE team_id = 572;
UPDATE teams SET team_name = 'Hatayspor', team_power = 6.81 WHERE team_id = 574;
UPDATE teams SET team_name = 'Giresunspor', team_power = 6.77 WHERE team_id = 605;
UPDATE teams SET team_name = 'Alanyaspor', team_power = 6.85 WHERE team_id = 619;
UPDATE teams SET team_name = 'Akhisarspor', team_power = 6.79 WHERE team_id = 631;
UPDATE teams SET team_name = 'Kasımpaşa', team_power = 6.83 WHERE team_id = 656;
UPDATE teams SET team_name = 'Balıkesirspor', team_power = 6.67 WHERE team_id = 1648;
UPDATE teams SET team_name = 'Yeni Malatyaspor', team_power = 6.78 WHERE team_id = 7297;
UPDATE teams SET team_name = 'BB Erzurumspor', team_power = 6.77 WHERE team_id = 9632;
